### ISSUE TITLE
Meldung : Fehler: Node-RED Webserver antwortet nicht.

### ISSUE THREAD

**Issue by guybrushix** [hobbyquaker/ccu-addon-node-red#6]
Hallo, ich komme leider gar nicht erst auf den Red Server. Meldung "Fehler: Node-RED Webserver antwortet nicht." Ein neustart bringt leider nichts. Muss ich zusätzlich zum Addon noch etwas installieren ?

Danke für die Hilfe im voraus 

```
# cat /var/log/messages | grep red

May 11 14:19:07 homematic-raspi user.info homematic: started node-red
May 11 14:19:09 homematic-raspi user.info node-red: [info]
May 11 14:19:09 homematic-raspi user.info node-red: Welcome to Node-RED
May 11 14:19:09 homematic-raspi user.info node-red: ===================
May 11 14:19:09 homematic-raspi user.info node-red: [info] Node-RED version: v0.18.4
May 11 14:19:09 homematic-raspi user.info node-red: [info] Node.js  version: v8.11.1
May 11 14:19:09 homematic-raspi user.info node-red: [info] Linux 4.14.34 arm LE
May 11 14:19:09 homematic-raspi user.info node-red: [info] Loading palette nodes
May 11 14:19:14 homematic-raspi user.info node-red: [info] Dashboard version 2.9.3 started at /addons/red/ui
May 11 14:19:14 homematic-raspi user.info node-red: [warn] Missing node modules:
May 11 14:19:14 homematic-raspi user.info node-red: [warn]  - node-red-contrib-ccu (0.1.9): ccu-submit
May 11 14:19:14 homematic-raspi user.info node-red: [info] Removing modules from config
May 11 14:19:14 homematic-raspi user.info node-red: [info] Settings file  : /usr/local/addons/node-red/settings.js
May 11 14:19:14 homematic-raspi user.info node-red: [info] User directory : /usr/local/addons/node-red/var
May 11 14:19:14 homematic-raspi user.info node-red: [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
May 11 14:19:14 homematic-raspi user.info node-red: [info] Flows file     : /usr/local/addons/node-red/var/flows.json
May 11 14:19:14 homematic-raspi user.info node-red: [info] Server now running at http://127.0.0.1:1880/addons/red/
May 11 14:19:14 homematic-raspi user.info node-red: [debug] loaded flow revision: aae644073a0132e7f22b2d6ee37bc171
May 11 14:19:14 homematic-raspi user.info node-red: [debug] red/runtime/nodes/credentials.load : no user key present
May 11 14:19:14 homematic-raspi user.info node-red: [debug] red/runtime/nodes/credentials.load : using default key
May 11 14:19:14 homematic-raspi user.info node-red: [debug] red/runtime/nodes/credentials.load : keyType=system
May 11 14:19:14 homematic-raspi user.info node-red: [info] Starting flows
May 11 14:19:14 homematic-raspi user.info node-red: [debug] red/nodes/flows.start : starting flow : global
May 11 14:19:14 homematic-raspi user.info node-red: [debug] red/nodes/flows.start : starting flow : 427fc89b.e34038
May 11 14:19:14 homematic-raspi user.info node-red: [debug] red/nodes/flows.start : starting flow : b47e4440.f97278
May 11 14:19:14 homematic-raspi user.info node-red: [debug] red/nodes/flows.start : starting flow : cdb7abff.3cf718
May 11 14:19:14 homematic-raspi user.info node-red: [debug] red/nodes/flows.start : starting flow : 4f28065f.6e1fb8
May 11 14:19:14 homematic-raspi user.info node-red: [debug] red/nodes/flows.start : starting flow : d2aa9e3f.51894
May 11 14:19:14 homematic-raspi user.info node-red: [debug] red/nodes/flows.start : starting flow : d93ee77.7acbf18
May 11 14:19:14 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] ccu-connection localhost
May 11 14:19:14 homematic-raspi user.info node-red: [info] [ccu-connection:localhost] paramsets loaded from /usr/local/addons/node-red/var/ccu_paramsets.json
May 11 14:19:14 homematic-raspi user.info node-red: [info] [ccu-connection:localhost] metadata loaded from /usr/local/addons/node-red/var/ccu_localhost.json
May 11 14:19:14 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] rega getChannels
May 11 14:19:14 homematic-raspi user.info node-red: [info] Started flows
May 11 14:19:14 homematic-raspi user.info node-red:  442
May 11 14:19:14 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] rega getRooms
May 11 14:19:14 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] rega getFunctions
May 11 14:19:14 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] rega getValues
May 11 14:19:15 homematic-raspi user.info node-red: [error] [ccu-connection:localhost] SyntaxError: Unexpected token
May 11 14:19:15 homematic-raspi user.info node-red:  in JSON at position 13296
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] rega getVariables
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] rpc.createClient ReGaHSS {"host":"localhost","port":1999}
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] rpc.createClient BidCos-RF {"host":"localhost","port":2001}
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] rpc.createClient HmIP-RF {"host":"localhost","port":2010}
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] rpc.createClient VirtualDevices {"url":"http://localhost:9292//groups"}
May 11 14:19:15 homematic-raspi user.info node-red: [info] [ccu-connection:localhost] rpc.createServer binrpc://127.0.0.1:2047
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] rpc > BidCos-RF init ["binrpc://127.0.0.1:2047","nr_BidCos-RF"]
May 11 14:19:15 homematic-raspi user.info node-red: [info] [ccu-connection:localhost] rpc.createServer http://127.0.0.1:2048
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] rpc > HmIP-RF init ["http://127.0.0.1:2048","nr_HmIP-RF"]
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] rpc > VirtualDevices init ["http://127.0.0.1:2048","nr_VirtualDevices"]
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost]     < HmIP-RF init ""
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] rpcCheckInit HmIP-RF 0 600
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] rpc < BidCos-RF system.listMethods ["nr_BidCos-RF"]
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost]     > BidCos-RF system.listMethods ["system.listMethods","setReadyConfig","newDevices","deleteDevices","listDevices","event","system.multicall"]
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] rpc < HmIP-RF listDevices ["nr_HmIP-RF"]
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost]     > HmIP-RF listDevices [{"ADDRESS":"000955699D3DFD","VERSION":1},{"ADDRESS":"000955699D3DFD:0","VERSION":1},{"ADDRESS":"000955699D3DFD:1","VERSION":1}]
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] rpc < HmIP-RF listDevices ["nr_VirtualDevices"]
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost]     > VirtualDevices listDevices []
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] rpc < BidCos-RF listDevices ["nr_BidCos-RF"]
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost]     > BidCos-RF listDevices [{"ADDRESS":"BidCoS-RF","VERSION":6},{"ADDRESS":"BidCoS-RF:0","VERSION":6},{"ADDRESS":"BidCoS-RF:1","VERSION":6},{"ADDRESS":"BidCoS-RF:2","VERSION":6},{"ADDRESS":"BidCoS-RF:3","VERSION":6},{"ADDRESS":"BidCoS-RF:4","VERSION":6},{"ADDRESS":"BidCoS-RF:5","VERSION":6},{"ADDRE
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] rpc < HmIP-RF deleteDevices ["nr_HmIP-RF",["000955699D3DFD","000955699D3DFD:0","000955699D3DFD:1"]]
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] deleteDevice HmIP-RF 000955699D3DFD
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] deleteDevice HmIP-RF 000955699D3DFD:0
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] deleteDevice HmIP-RF 000955699D3DFD:1
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost]     > HmIP-RF deleteDevices ""
May 11 14:19:15 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] saveMetadata /usr/local/addons/node-red/var/ccu_localhost.json
May 11 14:19:16 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] rpc < HmIP-RF newDevices ["nr_VirtualDevices",[{"TYPE":"VIR-LG-WHITE-DIM","SUBTYPE":"","ADDRESS":"OL-fenster","RF_ADDRESS":0,"CHILDREN":["OL-fenster:0","OL-fenster:1"],"PARENT":"","PARENT_TYPE":"","INDEX":0,"AES_ACTIVE":0,"PARAMSETS":"","FIRMWARE":"1.0.0","AVAILABLE_FIRMWARE":"1.0.0","UPDATABLE":tru
May 11 14:19:16 homematic-raspi user.info node-red: [debug] [ccu-connection:localhost] newDevice VirtualDevices OL-fenster
May 11 14:19:16 homematic-raspi user.info node-red: 11 May 14:19:16 - [red] Uncaught Exception:
May 11 14:19:16 homematic-raspi user.info node-red: 11 May 14:19:16 - TypeError: device.PARAMSETS.forEach is not a function
May 11 14:19:16 homematic-raspi user.info node-red:     at CcuConnectionNode.paramsetQueuePush (/usr/local/addons/node-red/lib/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:815:30)
May 11 14:19:16 homematic-raspi user.info node-red:     at CcuConnectionNode.newDevice (/usr/local/addons/node-red/lib/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:902:18)
May 11 14:19:16 homematic-raspi user.info node-red:     at devices.forEach.device (/usr/local/addons/node-red/lib/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:950:30)
May 11 14:19:16 homematic-raspi user.info node-red:     at Array.forEach (<anonymous>)
May 11 14:19:16 homematic-raspi user.info node-red:     at Object.newDevices (/usr/local/addons/node-red/lib/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:949:29)
May 11 14:19:16 homematic-raspi user.info node-red:     at Server.servers.(anonymous function).on (/usr/local/addons/node-red/lib/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:798:48)
May 11 14:19:16 homematic-raspi user.info node-red:     at emitThree (events.js:136:13)
May 11 14:19:16 homematic-raspi user.info node-red:     at Server.emit (events.js:217:7)
May 11 14:19:16 homematic-raspi user.info node-red:     at /usr/local/addons/node-red/lib/node_modules/node-red-contrib-ccu/node_modules/homematic-xmlrpc/lib/server.js:42:14
May 11 14:19:16 homematic-raspi user.info node-red:     at Deserializer.callback (/usr/local/addons/node-red/lib/node_modules/node-red-contrib-ccu/node_modules/homematic-xmlrpc/lib/deserializer.js:65:7)
```

**Comment by hobbyquaker** [comment]
sollte mit v0.0.20 gefixt sein.

**Comment by guybrushix** [comment]
Danke funktioniert.
