### ISSUE TITLE
Exception und danach nix mehr

### ISSUE THREAD

**Issue by Hypnos3** [hobbyquaker/ccu-addon-node-red#7]
Heute hat sich die ReGa und NodeRed aufgehangen 19:58.

Interessant ist, das es eine Exception von node-red gab:
```
May 15 18:41:05 homematic-raspi user.info node-red: [info] [function:only once in 35min] send true, be quiet
May 15 18:54:15 homematic-raspi user.info node-red: [error] [ccu-connection:Homematic] ping timeout HmIP-RF 626
May 15 19:06:45 homematic-raspi user.info node-red: [error] [ccu-connection:Homematic] ping timeout HmIP-RF 750
May 15 19:16:05 homematic-raspi user.info node-red: [info] [function:only once in 35min] quiet ends
May 15 19:24:15 homematic-raspi user.info node-red: [error] [ccu-connection:Homematic] ping timeout HmIP-RF 607
May 15 19:58:58 homematic-raspi user.info node-red: 15 May 19:58:58 - [red] Uncaught Exception:
May 15 19:58:58 homematic-raspi user.info node-red: 15 May 19:58:58 - TypeError: Cannot read property 'xml' of null
May 15 19:58:58 homematic-raspi user.info node-red:     at parseXml (/usr/local/addons/node-red/lib/node_modules/node-red-contrib-ccu/node_modules/homematic-rega/index.js:33:44)
May 15 19:58:58 homematic-raspi user.info node-red:     at Parser.<anonymous> (/usr/local/addons/node-red/lib/node_modules/node-red-contrib-ccu/node_modules/xml2js/lib/parser.js:303:18)
May 15 19:58:58 homematic-raspi user.info node-red:     at emitOne (events.js:116:13)
May 15 19:58:58 homematic-raspi user.info node-red:     at Parser.emit (events.js:211:7)
May 15 19:58:58 homematic-raspi user.info node-red:     at Parser.exports.Parser.Parser.parseString (/usr/local/addons/node-red/lib/node_modules/node-red-contrib-ccu/node_modules/xml2js/lib/parser.js
:313:16)
May 15 19:58:58 homematic-raspi user.info node-red:     at Parser.parseString (/usr/local/addons/node-red/lib/node_modules/node-red-contrib-ccu/node_modules/xml2js/lib/parser.js:5:59)
May 15 19:58:58 homematic-raspi user.info node-red:     at exports.parseString (/usr/local/addons/node-red/lib/node_modules/node-red-contrib-ccu/node_modules/xml2js/lib/parser.js:354:19)
May 15 19:58:58 homematic-raspi user.info node-red:     at Rega._parseResponse (/usr/local/addons/node-red/lib/node_modules/node-red-contrib-ccu/node_modules/homematic-rega/index.js:29:9)
May 15 19:58:58 homematic-raspi user.info node-red:     at Request.request [as _callback] (/usr/local/addons/node-red/lib/node_modules/node-red-contrib-ccu/node_modules/homematic-rega/index.js:61:22)
May 15 19:58:58 homematic-raspi user.info node-red:     at Request.self.callback (/usr/local/addons/node-red/lib/node_modules/node-red-contrib-ccu/node_modules/request/request.js:186:22)
May 15 19:58:58 homematic-raspi user.info node-red:     at emitTwo (events.js:126:13)
May 15 19:58:58 homematic-raspi user.info node-red:     at Request.emit (events.js:214:7)
May 15 19:58:58 homematic-raspi user.info node-red:     at Request.<anonymous> (/usr/local/addons/node-red/lib/node_modules/node-red-contrib-ccu/node_modules/request/request.js:1163:10)
May 15 19:58:58 homematic-raspi user.info node-red:     at emitOne (events.js:116:13)
May 15 19:58:58 homematic-raspi user.info node-red:     at Request.emit (events.js:211:7)
May 15 19:58:58 homematic-raspi user.info node-red:     at IncomingMessage.<anonymous> (/usr/local/addons/node-red/lib/node_modules/node-red-contrib-ccu/node_modules/request/request.js:1085:12)
May 15 19:59:16 homematic-raspi user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_BidCos-Wired","NEQ0308096:26","VALUE",327.000000}]}) on binary://127.0.0.1:2047/RPC2
:
May 15 19:59:21 homematic-raspi user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_BidCos-Wired","CENTRAL","PONG","hm-rpc.1"}]}) on binary://127.0.0.1:2047/RPC2:
May 15 19:59:32 homematic-raspi user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_BidCos-Wired","NEQ0308096:26","VALUE",326.000000}]}) on binary://127.0.0.1:2047/RPC2
:
May 15 19:59:59 homematic-raspi user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_BidCos-Wired","NEQ0308096:26","VALUE",327.000000}]}) on binary://127.0.0.1:2047/RPC2
:
May 15 20:00:14 homematic-raspi user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_BidCos-Wired","NEQ0308096:26","VALUE",326.000000}]}) on binary://127.0.0.1:2047/RPC2
:
May 15 20:00:40 homematic-raspi user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_BidCos-Wired","NEQ0308096:26","VALUE",327.000000}]}) on binary://127.0.0.1:2047/RPC2
:
May 15 20:00:51 homematic-raspi user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_BidCos-Wired","CENTRAL","PONG","hm-rpc.1"}]}) on binary://127.0.0.1:2047/RPC2:
May 15 20:00:55 homematic-raspi user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_BidCos-Wired","NEQ0308096:26","VALUE",326.000000}]}) on binary://127.0.0.1:2047/RPC2
:
May 15 20:01:20 homematic-raspi user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_BidCos-Wired","NEQ0308096:26","VALUE",327.000000}]}) on binary://127.0.0.1:2047/RPC2
:
May 15 20:01:29 homematic-raspi user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_BidCos-Wired","NEQ0308096:1","STATE",false}]}) on binary://127.0.0.1:2047/RPC2:
# 
```
Danach kommt nix mehr von node-red.

Die Rega hab ich mittels Kommandozeile neu gestartet und es läuft wieder alles, bis auf Node-red.

**Comment by hobbyquaker** [comment]
Node-RED lässt sich übrigens über `/etc/config/rc.d/node-red start` bzw `/etc/config/rc.d/node-red restart` neustarten.

**Comment by Hypnos3** [comment]
OK, Danke.

**Comment by Hypnos3** [comment]
Mittlerweile stürtzt die Rage nicht mehr ab. Dafür ist mir aber Node-Red schon 3-4 mal abgeschmiert. Das nur, wenn ich den client offen habe.

```
May 18 21:30:18 homematic-raspi user.info node-red: [info] [function:only once in 5min] send true, be quiet
May 18 21:30:49 homematic-raspi user.info node-red: [info] [function:only once in 5min] Quiet do nothing
May 18 21:35:49 homematic-raspi user.info node-red: [info] [function:only once in 5min] quiet ends
May 18 22:14:08 homematic-raspi user.info node-red: [info] Stopping modified flows
May 18 22:14:08 homematic-raspi user.info node-red: [info] Stopped modified flows
May 18 22:14:08 homematic-raspi user.info node-red: [info] Starting modified flows
May 18 22:14:08 homematic-raspi user.info node-red: [info] Started modified flows
May 18 22:15:50 homematic-raspi user.info node-red: 18 May 22:15:50 - [red] Uncaught Exception:
May 18 22:15:50 homematic-raspi user.info node-red: 18 May 22:15:50 - Error: connect ETIMEDOUT 192.168.178.35:8009
May 18 22:15:50 homematic-raspi user.info node-red:     at Object._errnoException (util.js:1022:11)
May 18 22:15:50 homematic-raspi user.info node-red:     at _exceptionWithHostPort (util.js:1044:20)
May 18 22:15:50 homematic-raspi user.info node-red:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
May 18 22:16:14 homematic-raspi user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_BidCos-Wired","NEQ0308096:26","      VALUE",327.000000}]}) on binary://127.0.0.1:2047/RPC2:
May 18 22:16:25 homematic-raspi user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_BidCos-Wired","NEQ0308096:26","      VALUE",326.000000}]}) on binary://127.0.0.1:2047/RPC2:
May 18 22:16:42 homematic-raspi user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_BidCos-Wired","CENTRAL","PONG",      "hm-rpc.1"}]}) on binary://127.0.0.1:2047/RPC2:
May 18 22:17:55 homematic-raspi user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_BidCos-Wired","NEQ0308096:26","      VALUE",327.000000}]}) on binary://127.0.0.1:2047/RPC2:
May 18 22:18:06 homematic-raspi user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_BidCos-Wired","NEQ0308096:26","      VALUE",326.000000}]}) on binary://127.0.0.1:2047/RPC2:
May 18 22:18:12 homematic-raspi user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_BidCos-Wired","CENTRAL","PONG",      "hm-rpc.1"}]}) on binary://127.0.0.1:2047/RPC2:
May 18 22:19:31 homematic-raspi user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_BidCos-Wired","NEQ0308096:26","      VALUE",327.000000}]}) on binary://127.0.0.1:2047/RPC2:
May 18 22:19:42 homematic-raspi user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_BidCos-Wired","NEQ0308096:26","      VALUE",326.000000}]}) on binary://127.0.0.1:2047/RPC2:
May 18 22:19:42 homematic-raspi user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_BidCos-Wired","CENTRAL","PONG",      "hm-rpc.1"}]}) on binary://127.0.0.1:2047/RPC2:
May 18 22:21:12 homematic-raspi user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_BidCos-Wired","NEQ0308096:26","      VALUE",327.000000}]}) on binary://127.0.0.1:2047/RPC2:
```

**Comment by hobbyquaker** [comment]
was lauscht bei Dir denn auf 192.168.178.35 port 8009?

**Comment by Hypnos3** [comment]
Ich hab das Modul "node-red-contrib-chromecast" installiert. Ich habe getestet ob ich auf dem Google Home Mini damit eine Sprachausgabe hinbekomme. Da ich noch CCU Protect installiert habe, musste ich dort noch die IP freischalten. Das funktioniert jetzt.
Also scheint dort das Problem gelegen zu haben.

**Comment by hobbyquaker** [comment]
Jo, ist aber unschön wenn der Chromecast node zum crash führt wenn er keine Verbindung aufbauen kann. Würde denke ich Sinn machen dort ein Issue aufzumachen, sollte keine große Sache sein das zu fixen. Ich denk derweil drüber nach ob es sinnvoll wär Node-RED im Falle eines Crashs automatisch neustarten zu lassen und wie ich das angehn könnt...

**Comment by Hypnos3** [comment]
Der Fehler war hier aber eindeutig vor dem Bildschirm.
